describe('Nav Link Test', () => {
    it('Tests links on navbar to make sure each page loads correctly', () => {
      cy.visit('https://www.aumni.fund/')
        .wait(5000)

      cy.get(`.w-dropdown-list`)
        .invoke('show')
      cy.get('.dd-navlink')
        .contains('The Basics')
        .click({force: true})
        .wait(5000)

      cy.get(`.w-dropdown-list`)
        .invoke('show')
      cy.get('.dd-navlink')
        .contains('Investment')
        .click({force: true})
        .wait(5000)

      cy.get(`.w-dropdown-list`)
        .invoke('show')
      cy.get('.dd-navlink')
        .contains('Finance')
        .click({force: true})
        .wait(5000)
        
      cy.get(`.w-dropdown-list`)
        .invoke('show')
      cy.get('.dd-navlink')
        .contains('Legal')
        .click({force: true})
        .wait(5000)

      cy.get(`.w-dropdown-list`)
        .invoke('show')
      cy.get('.dd-navlink')
        .contains('Analytics')
        .click({force: true})
        .wait(5000)

    })
})

describe('Login Test', ()=> {
  it('Clicks "Login" and tries to login', () => {
    cy.visit('https://www.aumni.fund/')
        .wait(5000)
    cy.get('.login')
        .click()
    cy.get('button')
        .click()
    cy.get('#1-email')
        .click()
        .type('username@gmail.com', {force: true})
    cy.get('.auth0-lock-input-show-password > .auth0-lock-input-block > .auth0-lock-input-wrap > .auth0-lock-input')
        .click()
        .type('password', {force: true})
    cy.get('.auth0-label-submit').click()
  })
})
